version: '3.8'

services:
  pipeline-manager:
    build: .
    image: pipeline-manager:latest
    volumes:
      # Mount the configuration database directory (read/write)
      - ./data:/config
      # Mount the sensor database in read-only mode - adjust path as needed
      - ../sample-sensor/data:/sensor-data:ro
    environment:
      - PYTHONUNBUFFERED=1
    # Default command shows current configuration from separate config database
    command: ["python", "pipeline_controller.py", "--config-db", "/config/pipeline_config.db", "get"]