services:
  sensor-simulators:
    image: alpine:latest
    pull_policy: always
    restart: unless-stopped
    command: sh /app/sensor-simulator.sh
    volumes:
      - ./config:/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./exports:/app/exports
      - ./sensor-simulator.sh:/app/sensor-simulator.sh
